(()=>{
const panels=[...document.querySelectorAll('[data-panel]')],links=[...document.querySelectorAll('.tab-link')],valid=new Set(panels.map(p=>p.dataset.panel));
function show(name,push=true){name=valid.has(name)?name:'bio';panels.forEach(p=>{const on=p.dataset.panel===name;p.hidden=!on;p.classList.toggle('active',on)});links.forEach(a=>{const on=a.dataset.tab===name;a.classList.toggle('active',on);if(a.closest('nav'))on?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current')});if(push&&location.hash!==`#${name}`)history.pushState(null,'',`#${name}`);scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});document.title=name==='bio'?'Shayne Magstadt | Wildfire, AI & Geospatial Science':`${name==='research'?'Research':'Marbles'} | Shayne Magstadt`}
links.forEach(a=>a.addEventListener('click',e=>{e.preventDefault();show(a.dataset.tab)}));addEventListener('popstate',()=>show(location.hash.slice(1),false));show(location.hash.slice(1)||'bio',false);
const topbar=document.getElementById('topbar');addEventListener('scroll',()=>topbar.classList.toggle('scrolled',scrollY>24),{passive:true});document.getElementById('year').textContent=new Date().getFullYear();
const filters=[...document.querySelectorAll('[data-filter]')],papers=[...document.querySelectorAll('.paper')];filters.forEach(b=>b.addEventListener('click',()=>{filters.forEach(x=>{const on=x===b;x.classList.toggle('active',on);x.setAttribute('aria-pressed',on)});papers.forEach(p=>p.classList.toggle('filtered',b.dataset.filter!=='all'&&!p.dataset.topics.split(' ').includes(b.dataset.filter)))}));
const dialog=document.getElementById('paperDialog'),close=dialog.querySelector('.close'),dimg=dialog.querySelector('.dialog-image img'),dmeta=dialog.querySelector('.dialog-image span'),dtitle=dialog.querySelector('h2'),dsum=dialog.querySelector('.summary'),dmethod=dialog.querySelector('.method'),dfinding=dialog.querySelector('.finding'),dpdf=dialog.querySelector('a');
document.querySelectorAll('.paper-open').forEach(b=>b.addEventListener('click',()=>{const p=b.closest('.paper');dimg.src=p.dataset.image;dimg.alt=p.querySelector('img').alt;dmeta.textContent=p.dataset.meta;dtitle.textContent=p.dataset.title;dsum.textContent=p.dataset.summary;dmethod.textContent=p.dataset.method;dfinding.textContent=p.dataset.finding;dpdf.href=p.dataset.pdf;dialog.showModal();document.body.classList.add('lock')}));function closeDialog(){dialog.close();document.body.classList.remove('lock')}close.addEventListener('click',closeDialog);dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog()});dialog.addEventListener('close',()=>document.body.classList.remove('lock'));
const gallery=[{src:'assets/marble-galaxy.webp',alt:'Blue, teal, and gold galaxy-style glass marble',title:'Blue Galaxy',desc:'Blue-and-gold currents with layered glass depth and bright suspended highlights.'},{src:'assets/marble-studio.jpg',alt:'Clear spiral glass marble resting on a turned wooden bowl',title:'Studio Spiral',desc:'A clear optical spiral photographed against the warmth and grain of turned wood.'}],light=document.getElementById('lightbox'),limg=light.querySelector('img'),lindex=light.querySelector('figcaption small'),ltitle=light.querySelector('h2'),ldesc=light.querySelector('figcaption p');let current=0,last=null;function render(i){current=(i+gallery.length)%gallery.length;const x=gallery[current];limg.src=x.src;limg.alt=x.alt;lindex.textContent=`Study ${String(current+1).padStart(2,'0')} / ${String(gallery.length).padStart(2,'0')}`;ltitle.textContent=x.title;ldesc.textContent=x.desc}function openLight(i,t){last=t;render(i);light.hidden=false;document.body.classList.add('lock');light.querySelector('.light-close').focus()}function closeLight(){light.hidden=true;document.body.classList.remove('lock');last?.focus()}
document.querySelectorAll('.gallery-open').forEach(b=>b.addEventListener('click',()=>openLight(Number(b.dataset.index),b)));light.querySelector('.light-close').addEventListener('click',closeLight);light.querySelector('.prev').addEventListener('click',()=>render(current-1));light.querySelector('.next').addEventListener('click',()=>render(current+1));light.addEventListener('click',e=>{if(e.target===light)closeLight()});addEventListener('keydown',e=>{if(!light.hidden){if(e.key==='Escape')closeLight();if(e.key==='ArrowLeft')render(current-1);if(e.key==='ArrowRight')render(current+1)}});
})();
